<?php
namespace moxuandi\umeditor;

use Yii;
use yii\base\Action;
use yii\helpers\Json;
use moxuandi\helper\Uploader;

/**
 * UMeditor 接收上传图片控制器
 *
 * @author  zhangmoxuan <1104984259@qq.com>
 * @link  http://www.zhangmoxuan.com
 * @QQ  1104984259
 * @Date  2017/7/12
 */
class UMeditorAction extends Action
{
    public $config = [];  // 配置接口, 参考 init() 中的 $_config


    public function init()
    {
        yii::$app->request->enableCsrfValidation = false;  // 关闭csrf
        $_config = [  // 默认的上传配置信息
            'maxSize' => 5*1024*1024,  // 上传大小限制, 单位B, 默认5MB, 注意修改服务器的大小限制
            'allowFiles' => ['.png', '.jpg', '.jpeg', '.gif', '.bmp'],  // 上传图片格式显示
            'thumbStatus' => true,  // 是否生成缩略图
            'thumbWidth' => 300,  // 缩略图宽度
            'thumbHeight' => 200,  // 缩略图高度
            'thumbCut' => 1,  // 生成缩略图的方式, 0:留白, 1:裁剪
            'pathFormat' => 'uploads/image/{yyyy}{mm}/{yy}{mm}{dd}_{hh}{ii}{ss}_{rand:4}',  // 上传保存路径, 可以自定义保存路径和文件名格式
                /* {filename} 会替换成原文件名[要注意中文文件乱码问题] */
                /* {rand:6} 会替换成随机数, 后面的数字是随机数的位数 */
                /* {time} 会替换成时间戳 */
                /* {yyyy} 会替换成四位年份 */
                /* {yy} 会替换成两位年份 */
                /* {mm} 会替换成两位月份 */
                /* {dd} 会替换成两位日期 */
                /* {hh} 会替换成两位小时 */
                /* {ii} 会替换成两位分钟 */
                /* {ss} 会替换成两位秒 */
                /* 非法字符 \ : * ? " < > | */
                /* 具请体看线上文档: http://fex.baidu.com/ueditor/#server-path 3.1 */
            'saveDatabase' => false,  // 保存上传信息到数据库
        ];
        $this->config = array_merge($_config, $this->config);
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $up = new Uploader('upfile', $this->config, 'upload', $this->config['saveDatabase']);
        $info = [
            'originalName' => $up->realName,
            'name' => $up->fileName,
            'url' => $up->fullName,
            'size' => $up->fileSize,
            'type' => $up->fileType,
            'state' => $up->stateInfo,
        ];
        if($callback = yii::$app->request->get('callback')){
            echo '<script>' . $callback . '(' . Json::encode($info) . ')</script>';
        }else{
            echo Json::encode($info);
        }
    }
}
